### ISSUE TITLE
[Hestia] SalesOrderItems to be duplicated if not enough stock

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#15]
We need to keep track if there are items that are ordered but are not present in the warehouse/inventory.

If the items are not sufficient duplicate the SalesOrderItems by sufficient/unsufficient.

Example:
SalesOrderItem -  Iphone 15 - 10 units ; Inventory has 5 units:
- SalesOrderItem 1 - 5 units - sufficient
- SalesOrderItem 2 - 5 units - unsufficient

**Comment by MinaDoncheva** [comment]
fixed with https://github.com/codbex/codbex-orders/pull/17, https://github.com/codbex/codbex-order-inventory-ext/commit/638ac2b7bc678435a052f4c65cb5ea472d47df54, https://github.com/codbex/codbex-order-inventory-ext/commit/2fb412a502b085af5146d2175388027384a1b87d and https://github.com/codbex/codbex-order-inventory-ext/commit/61d7d8519200dc6fbcca67ea093f2ca5ec2fbcb4
